### ISSUE TITLE
"Can't found address block" or "segmentation fault"

### ISSUE THREAD

**Issue by gramian** [skruug/silm-extract#1]
I am testing `silm-extract` with various `.IO` files and I get either "Can't found address block" or "segmentation fault" and no outputs are generated at all.

**Comment by skruug** [comment]
Hi, I’v not tested it with pc versions of silmarils games extensively. Decompressor was only working on big endian games till recently, PC support was added hastily without much testing. If you want I can have a look. Can you tell me what kind of game you are trying to extract data from and on what platform are you using?

**Comment by gramian** [comment]
I was testing MS-DOS PC versions of Ishar games (1,2,3). I am on Macbook M2 (arm64) and compiled as suggested in Xcode.

Thanks!

**Comment by skruug** [comment]
I see where the problem is. In previous version I used heuristic to find adress block. That code was later removed and replaced by code from Atari Falcon version of Ishar and never tested on pc version.
I'll fix it.

**Comment by gramian** [comment]
Great! Happy to test.

**Comment by skruug** [comment]
Fixed

**Comment by gramian** [comment]
Awesome, 1d69feceb627e7cf28cb44696f7ec93cdfd6b433 fixes it for me. Thanks you
